import Navbar from '@/app/components/navbar/Navbar'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import { ThemeProvider } from '@/app/providers/ThemeProvider'
import { cn } from '@/lib/utils'
import { ConfettiProvider } from '@/app/providers/ConfettiProvider'
import ToasterProvider from './providers/ToasterProvider'
import getCurrentUser from './actions/getCurrentUser'
import ModalProvider from './providers/ModalProvider'
import LocoScroll from './components/LocoScroll'
import BottomNavbar from './components/bottom-navbar/BottomNavbar'

const font = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Univibe',
  description: 'Generated by create next app',
}


export default async function RootLayout({
  children,
  
}: {
  children: React.ReactNode
}) {
  const currentUser = await getCurrentUser()
  return (
    <html lang="en">
      <body className={cn(
          font.className,
          "bg-white dark:bg-neutral-900"
      )}>
          <ThemeProvider
            attribute='class'
            defaultTheme='light'
            enableSystem = {false}
            storageKey='univibe-key'
            
          >
            <ToasterProvider />
            <ConfettiProvider />
            <Navbar currentUser = {currentUser} />
            <ModalProvider/>
            <div className='pb-20 pt-28'>
              <LocoScroll>
                {children}
              </LocoScroll>
            </div>
            <BottomNavbar currentUser = {currentUser} />
          </ThemeProvider>
      </body>
    </html>
  )
}
